spring.application.name=ecom-application

spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:test

management.endpoints.web.exposure.include = *

endpoint.health.show.details = always


#spring.jpa.show-sql = true;
#spring.jpa.hibernate.ddl-auto = create;
